### ISSUE TITLE
When call `/game-s`，it triggers OpenAI message reply and search game command.

### ISSUE THREAD

**Issue by dianhsu** [dianhsu/dianbot#5]
![image](https://github.com/dianhsu/dianbot/assets/50162344/676090d5-ec38-44d6-91f0-357a2f5ff77b)

**Comment by dianhsu** [comment]
Expect result is attached as below image.

![image](https://github.com/dianhsu/dianbot/assets/50162344/ef9f3777-d3be-43cc-9c52-8b5928873c57)

**Comment by herestars** [comment]
## BUG
-  [ ] #5
